### ISSUE TITLE
[Suggestion] Make config option for a list of weapons that kills undead anyways

### ISSUE THREAD

**Issue by Warrock3280** [TheIllusiveC4/Consecration#11]
Add to config a list of items that kills undeads even without any enchantments
### OR / AND
Make an option for damage threshold enough to kill undead (maybe undead's total HP multiplier)
Because some weapons seems enough powerful to totally annihilate something like zombie but eventually cannot even finish him off.

**Comment by TheIllusiveC4** [comment]
I'm looking into adding the first suggestion. It's just a little complicated since I'd either have to differentiate between weapons that have materials (like diamond sword, silver pickaxe, etc.) and weapons that are just items or only allow the former.

I'm not going to add a damage threshold option though. The whole point is that, no matter how damage you do, the undead won't die without the proper type of damage.
