### ISSUE TITLE
Incompatibility with custom npc ( 1.12.2 and forge 2705 )

### ISSUE THREAD

**Issue by Azvalk** [TheIllusiveC4/Consecration#19]
Hi :D
Your mod is great, and fits perfectly with Overlord mod, so it's why I used it in my modpack.. 
and so I encounter a problem..
Here it is:

https://pastebin.com/N44i9ym0

Custom npc is completely inoperant, it's impossible to summon a npc with the tool, and this error occurs..
I don't understand error like that, so, I don't know if it's your mod, or custom npc who's cause this issue.. But, your are a more active developper than Noppes right know, so I come to you first. ^^

**Comment by TheIllusiveC4** [comment]
As far as I can tell, this is a Custom NPC issue. That particular function isn't doing anything special on my end, yet Custom NPC is somehow throwing an NPE through this call. I'm not sure why since the mod doesn't have visible source code, but I think it'd be best to bring this up with them instead.
