### ISSUE TITLE
[Suggestion][Config] Undead movement speed modifier

### ISSUE THREAD

**Issue by CREEATION** [TheIllusiveC4/Consecration#32]
I currently use [_In Control!_](https://minecraft.curseforge.com/projects/in-control) to change the movement speed and health of undead mobs, but I think it would be a good compensation for the additional difficulty to kill them in Consecration, too. Or it would be for me, at least 🐢

Using Consecration alongside _In Control!_ would do the job, but then again I could remove over 50% off of my `spawn.json` in _In Control!_.

**Comment by TheIllusiveC4** [comment]
I've implemented something like this, but I'm not sure it's exactly what you wanted or envisioned. There's now a config option for bonus speed modifier that will grant undead a movement speed bonus unless you smite them and take away that ability (just like the damage reduction and health regen).

**Comment by CREEATION** [comment]
Of course, I forgot the most important part 🤦‍♀️ 
In my script, I'm making undead mobs have double their health and, to compensate for their bonus health, move just half their original speed.

Your implementation goes nice with the overall concept of Consecration, so that's great 🐢

If I set the movement speed bonus to "0.5", I assume they will just move half their original speed.
But would smiting make them go faster again? 👀

**Comment by TheIllusiveC4** [comment]
Ah, then this unfortunately may not work with your idea. I worded it that way because it's strictly a bonus, it only adds to the movement speed. And I don't really want to make it work both ways because it'd be odd if you set their movement speed lower and then smiting makes them faster, like you mentioned. I'd prefer to keep the smiting mechanic focused and streamlined without introducing extraneous attribute editing.

**Comment by CREEATION** [comment]
Makes sense! Thanks for the quick update 💃
