### ISSUE TITLE
(Compatibility) Bewitchment compatibility

### ISSUE THREAD

**Issue by Azmalent** [TheIllusiveC4/Consecration#39]
Bewitchment has a holy water potion that doesn't work with Consecration when added to the config (it seems that it's not registered as a potion _type_, which is what Consecration expects)

**Comment by TheIllusiveC4** [comment]
Hm, interesting. I'll look into it.

**Comment by TheIllusiveC4** [comment]
I've been working on this on and off, but it looks like Bewitchment has made some big changes in the last month. After trying to implement compatibility with the new changes, it looks like it won't be possible due to the way that the Holy Water from Bewitchment deals damage. 

Specifically, it doesn't give any information that I can hook into to identify the damage it deals as "holy". I cannot hook into the potion entity to try and parse the potion effects nor can I evaluate the damage type because it deals generic magic damage. So unfortunately, my hands are tied at the moment.

**Comment by Sunconure11** [comment]
I created a pull for adding it to the config. Test it to see if it works.

Note that recently a coremod had to be added to BW in light of some potion shenanigans.

**Comment by Sunconure11** [comment]
I can bring one of the coders to look at this, though, if it's still having issues as of the latest update. @anqingchen

**Comment by TheIllusiveC4** [comment]
The proposed change to the config, while necessary, wouldn't fix the issue entirely (assuming the latest release of Bewitchment is up-to-date in this regard).

[This line](https://github.com/Um-Mitternacht/Bewitchment/blob/44e27eddfe6c6b8deca1de7a5d3ff0d7a5bdc97a/src/main/java/com/bewitchment/common/potion/PotionHolyWater.java#L24) needs to be updated to include information about the potion entity performing the damage, largely like what vanilla does for its instant effects. So, something like `living.attackEntityFrom(DamageSource.causeIndirectMagicDamage(source, indirectSource), 8 * (amplifier + 1));`. Otherwise, that information is lost and Consecration can't identify the potion effect.

**Comment by Sunconure11** [comment]
Alright, I've implemented your line.
