### ISSUE TITLE
[SUGGESTION] Command to dump all available materials

### ISSUE THREAD

**Issue by Sunconure11** [TheIllusiveC4/Consecration#46]
This would be useful for modpack devs, so they can define certain materials a bit better, for the purposes of smiting mobs.

**Comment by TheIllusiveC4** [comment]
I don't keep any sort of registry of available materials, especially since many mods have different ways of implementing the idea of a "material". All Consecration does is take the material names listed in its config and use that to test against a particular mod's materials, which often times needs special parsing in itself and is evaluated at the time of smiting. For example, some mods require that I dig through their tools/weapons' NBT data to find the right material name.

To figure out these names, modpack devs will need to look into each mod's source code or ask their devs for the material names.
