### ISSUE TITLE
Tetrapak : Modular sword material not recognised

### ISSUE THREAD

**Issue by MiteEnBois** [TheIllusiveC4/Consecration#66]
#### Versions:
* Consecration: consecration-forge-1.18.2-5.0.0.2
* Forge: 40.1.80 for 1.18.2
* Tetra: 1.18.2-4.9.3
#### Steps to Reproduce:
1. add a material as holy material, like minecraft:gold (for the record, the material itself doesn't matter)
2. make a vanilla gold sword : it applies the debuff
3. make a vanilla gold pick : it applies the debuff
4. make any sword, like an iron sword, and change the blade into gold : it doesn't apply the debuff
5. make any sword and make it entirely golden : doesn't apply the debuff
6. even making a gold sword and putting a gold blade doesn't apply the debuff

I tried with a clean install with only forge, consecration, tetra and it's dependency (mutil)
From what i can see, the code finds the material of items by checking the repair material of the item, i.e. the item needed to repair the sword in an anvil. As tetra items cannot be repaired this way, the mod cannot get the repair material, so they can't determine if it's holy or not.

Also, side note : can you put the default holy material as something other than "silver", as it's not a valid registry name under most circumstance, so people like myself don't know to include the name of the registry.

**Comment by TheIllusiveC4** [comment]
This is less of a bug and more a feature that had not been re-added. I have now released an update with integrations for Tetra and other mods that use material systems that differ from vanilla's.

> Also, side note : can you put the default holy material as something other than "silver", as it's not a valid registry name under most circumstance, so people like myself don't know to include the name of the registry.

This was a bug, the entries are not meant to be namespaced. Namespacing the entries was the workaround, but I have now fixed this bug so that entries like "silver" or "gold" will work as it did in previous versions. The workaround of using namespaced entries will still work for vanilla behavior, but mod integrations will rely on namespace-less entries going forward.
