### ISSUE TITLE
Haste potions from prelaw's tremors turn into consecration potions in the brewing stand...

### ISSUE THREAD

**Issue by Blugori** [TheIllusiveC4/Consecration#68]
Versions : 

Consecration : 5.0.1.1
Forge : 40.1.86
Spelunker's charm (prelaws tremors) : 2.6.0
JEI : 10.2.1.283

I tried to brew a long haste potion from prelaws tremors, I put an haste potion on the bottom slot and redstone on top.
After brewing, I received a consecration potion level 2 instead of a long haste potion.

And I noticed (not related) that the ingredient for the consecration potion lvl 2 is redstone, but should'nt it be glowstone dust for consistency ? Maybe it's intentional idk.

**Comment by TheIllusiveC4** [comment]
Unfortunately the mod in question seems to have disappeared off the face of the internet so I can no longer fix this compatibility error. However, as for the Redstone issue, you are correct. It should be Glowstone Dust. Maybe it was intentional at one point and I just forgot the reason, but I have addressed this by changing it to the correct recipe in 1.19.2+. It will remain the same in previous versions since I do not want to introduce a recipe change to a stable version.
